### ISSUE TITLE
.eslintrc.json

### ISSUE THREAD

**Issue by Lavve** [Lavve/MMM-MagicMover#11]
@KristjanESPERANTO  I can't find any info on what rules to apply in the eslint config. Do you have any suggestions or example regarding this?

**Comment by KristjanESPERANTO** [comment]
I have created a PR for this :slightly_smiling_face:. Feel free to ask if anything is unclear. ESLint is currently undergoing a transition from the classic configuration to the so-called flat config. This might be a bit confusing if you didn't know ESLint before.

**Comment by Lavve** [comment]
Thank you so much for your help in this issue.

**Comment by KristjanESPERANTO** [comment]
I'm glad I could help :smiley:

By the way, your module is currently one of the few in which no more issues have been identified during [the module analysis](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/blob/main/result.md) :rocket:
