### ISSUE TITLE
Modules are colliding with each other.

### ISSUE THREAD

**Issue by alebrug77** [Lavve/MMM-MagicMover#2]
Modules are colliding with each other after update. Please fix it!

**Comment by Klantkent** [comment]
Can confirm this at my RSS feed that is in position "top_center" is now pushed to the right and is colliding with the weather module.

**Comment by Lavve** [comment]
@alebrug77 and @Klantkent, did the last commit solve the issue?

**Comment by Klantkent** [comment]
@Lavve Seems to work now. Nice work! :)
