### ISSUE TITLE
Changing branch name borks updates

### ISSUE THREAD

**Issue by dathbe** [Lavve/MMM-MagicMover#7]
Bad news.  Changing the branch name from `master` to `main` prevents the use of `git pull` to update the module.  Given that this is an entirely cosmetic change that requires users to delete the folder and reinstall it, I would recommend going back.  Sorry for making you change it and change it back.

**Comment by Lavve** [comment]
Oh, right... Forgot about that. Not your fault, thank you for the heads up though!
